<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

theme: jekyll-theme-midnight
title: Welcome! 
description: I'm glad you're here.

<header id="header">...</header>

<section id="about me">...</section>

<section id="projects">...</section>

<section id="contact">...</section>

<section id="footer">...</section>

</body>

</html>
